# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSecurityConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_after', models.IntegerField(default=600, help_text=b'Logout after inactivity, seconds', verbose_name=b'Logout after')),
                ('warn_after', models.IntegerField(default=540, help_text=b'Warn user about inactivity, seconds', verbose_name=b'Warn after')),
            ],
            options={
                'verbose_name': 'Session Security Configuration',
            },
        ),
    ]
